/********************************************************************
* data_showDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error data_showDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtabledata_showDict();
extern void G__cpp_setup_inheritancedata_showDict();
extern void G__cpp_setup_typetabledata_showDict();
extern void G__cpp_setup_memvardata_showDict();
extern void G__cpp_setup_globaldata_showDict();
extern void G__cpp_setup_memfuncdata_showDict();
extern void G__cpp_setup_funcdata_showDict();
extern void G__set_cpp_environmentdata_showDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "data_show.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__data_showDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__data_showDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__data_showDictLN_TList;
extern G__linked_taginfo G__data_showDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__data_showDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__data_showDictLN_TQObjSender;
extern G__linked_taginfo G__data_showDictLN_TGWindow;
extern G__linked_taginfo G__data_showDictLN_TGMainFrame;
extern G__linked_taginfo G__data_showDictLN_TRootEmbeddedCanvas;
extern G__linked_taginfo G__data_showDictLN_MyMainFrame;

/* STUB derived class for protected member access */
