data_show: data_show.h data_show.cpp
	g++ `root-config --cflags --glibs` -o data_show data_show.cpp data_showDict.cpp


#main: main.cc
#	g++ -pthread -m32 -I/usr/include/root  -L/usr/lib/root -lCore -lCint -lRIO -lNet -lHist -lGraf -lGraf3d -lGpad -lTree -lRint -lPostscript -lMatrix -lPhysics -lMathCore -lThread -pthread -lm -ldl -rdynamic main.cc -o a.out
